### ISSUE TITLE
Not working for VSCode v1.16

### ISSUE THREAD

**Issue by coodoo** [monofon/hindent-format#4]
Just installed `hindent` and this plugin, pressed `cmd-ctrl-f` trying to format the source but to no avail, same goes for formatting selected code blocks.

Running via cli worked fine `hindent Main.hs`.

Is there anything I shall configure or pay attention to? Thanks.

**Comment by caelaxie** [comment]
I have the same problem as well. The extension does not work for the lasted version of VSCode (v1.17) but hindent works well on terminal.

**Comment by dogweather** [comment]
Works for me in v1.19.3.

**Comment by monofon** [comment]
I cannot reproduce that failure. Do you use any other plugins that install competing formatters for Haskell documents?

**Comment by monofon** [comment]
There is a palette command now, that you can use invoke the formatter directly.
