### ISSUE TITLE
Difficult to make work when `hindent` is not on the PATH

### ISSUE THREAD

**Issue by tillydray** [monofon/hindent-format#6]
I have to use this workspace setting because we are using a hindent executable which references a hindent.yaml, so if anyone else is having troubles this may help you,

`"hindentFormat.command": "<ABSOLUTE_PATH>/stack exec hindent -- --line-length 100"
`

**Comment by monofon** [comment]
hindent should now automatically pick up the `.hindent.yaml` file from either the workspace directory or the users home directory. Providing commandline arguments will now no longer work.
